/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bridgelabz.cabinvoicegenerator;

public class CabInvoiceGenerator {
	private static final double MINIMUM_COST_PER_KM = 10;
	private static final int COST_PER_TIME = 1;
	private static final double MINIMUM_FARE = 5;
	InvoiceService invoiceservice = new InvoiceService();
	public double calculateFare(double distance, int time) {
		double totalFare = distance * MINIMUM_COST_PER_KM + time * COST_PER_TIME;
		return Math.max(totalFare, MINIMUM_FARE);
	}

	public double calculateFare(Ride rides[]) {
		double totalFare = 0;
		for(Ride ride:rides) {
			totalFare += this.calculateFare(ride.distance,ride.time);
		}
		return totalFare;

	}

	public InvoiceSummary getSummary(Ride[] rides) {
		
		return new InvoiceSummary(rides.length,calculateFare(rides));
	}

	public InvoiceSummary getSummaryByUserId(String userId) {
		
		
		Ride[] ridesArray = new Ride[invoiceservice.getRidesList(userId).size()];
		ridesArray = invoiceservice.getRidesList(userId).toArray(ridesArray);
		return getSummary(ridesArray);
	}
}
